### PR TITLE
Fix R200 color cloud misalignment by using rectified color calibration

### PR DESCRIPTION
**Pull request by skohlbr**
This PR fixes the cloud/color camera alignment issues reported in issues stated below.
 
Fixes Issue: #30,  #184, #201, #233

Changes proposed in this pull request:
- Use rectified camera stream calibration instead of unrectified. It has to be noted that even just performing this change (and leaving color image retrieval as-is) vastly improves point cloud alignment (reducing error from ~9 pixels to maybe ~1 pixel in most image regions).
- Use the rectified color stream consistently for the R200. As a lot of the stream handling is done in base_nodelet for all camera types, performing the necessary changes without breaking other cameras (SR300 etc.) is not trivial. As the calibrated color image is published now, it has been remapped in the [nodelet_rgbd.launch.xml](https://github.com/skohlbr/realsense/blob/8d008af73bc2a5d25263ba11bdf61b5ce729370b/realsense_camera/launch/includes/nodelet_rgbd.launch.xml#L67) file. As a side effect, the rectification plugin loaded as part of the rgbd launch setup now throws ROS_WARNs about missing the image_color topic.

Looking for feedback by the maintainers, as this PR obviously cannot be merged right now without breaking other Realsense camera (SR300 etc.) use with the driver. See #201 for details of how this PR came about (screenshots etc.).

### CODE REVIEW

**Comment by skohlbr** [comment]
Updated PR and initial description.

**Comment by dorodnic** [comment]
Hi @skohlbr 
Thank you for taking the time to dig into this! We will test and see how to integrate with other devices.

**Comment by compiaffe** [comment]
@dorodnic @icarpis Any news on this one?

**Review by icarpis — APPROVED** [review]

**Comment by fmessmer** [comment]
@skohlbr @icarpis 
To be straight, I'm non perception expert...I just experienced that https://github.com/intel-ros/realsense/pull/261/files#diff-bc72946ee2b0a49ae6c992ef05d4f704R75 breaks the perception topic pipeline for our zr300 cameras...
As stated in the PR description, this has been warned about...however, I'm missing a solution how users for other cameras could guarantee their previous behavior?

Does the `else if (stream_index == RS_STREAM_COLOR)` part affect the zr300, too?
Should/Could the `rgb_processing` be turned off for zr300, too?
If the remap is kind of r200-specific, why was it not done in the specific launch file?
Could the remap be toggled with an `unless` argument - which defaults to false?

**Pull request merged**
