### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by ooeygui**

### CODE REVIEW

**Comment by nicolas-schreiber** [comment]
I attempted to use this on an up to date Windows and got following error message:

`Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Failed to load library E:/PROJECTS/ALR/catkin_ws/devel\bin/realsense2_camera.dll. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = E:/PROJECTS/ALR/catkin_ws/devel\bin/realsense2_camera.dll)`

**Comment by ooeygui** [comment]
@nicolas-schreiber I'll take a look. That dll should come from the vcpkg.

**Comment by nicolas-schreiber** [comment]
That file actually exists at that location, so I am quite confused by this.
Just for reference, in the devel/bin folder there are following files:
ddynamic_reconfigure.pdb
realsense2_camera.dll
realsense2_camera.dll.manifest
realsense2_camera.ilk
realsense2_camera.pdb
ddynamic_reconfigure.dll
ddynamic_reconfigure.dll.manifest
ddynamic_reconfigure.ilk

**Comment by ooeygui** [comment]
@nicolas-schreiber Thanks for catching this. 
This change was missing a mapping from DebWithRelInfo to Release, so Cmake was picking up the debug version of the realsense driver from vcpkg. This works around a vcpkg issue and is documented here: https://ms-iot.github.io/ROSOnWindows/GettingStarted/UsingVCPKG.html.

**Comment by michael-chikamchun** [comment]
Hi @nicolas-schreiber, were you able to get this working without issues on windows? 
Thank you.

**Comment by nicolas-schreiber** [comment]
Hi, yes, after this it successfully worked with Melodic in Windows 10 1909

**Pull request merged**
