### PR TITLE
Make building ROS unit tests optional

### PR DESCRIPTION
**Pull request by rojkov**
ROS users don't always need unit tests built with the driver together,
so make them conditional.

Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@linux.intel.com>

### CODE REVIEW

**Comment by mdhorn** [comment]
@rojkov Fails to builds in the ROS Build Farm. Please fix.

**Comment by mdhorn** [comment]
@rojkov I'm not opposed to the idea of this change, but I do think that if someone is downloading this code, and building it for ROS, then they have an intention to make changes. If they are making changes, then they should be running the unit tests before submitting a pull request. 
At the moment this doesn't build.

**Comment by rojkov** [comment]
@mdhorn Well, the problem with the unit tests is that it's not an easy task to reproduce the environment the tests are run in. :)

I spent yesterday to do exactly that, but after many bumps I've finally ended up with the problem fixed in https://github.com/IntelRealSense/librealsense/pull/342. I wonder if there is a way to work it around without having it propagated to the `http://packages.ros.org/ros/ubuntu` package repository or setting up an Ubuntu host.

**Comment by rojkov** [comment]
Fixed the build.
Turned out to be a peculiarity of `find_package`'s syntax.

**Comment by rojkov** [comment]
@mdhorn is this PR ok now to merge?

**Review by mdhorn — APPROVED** [review]
Unit tests still available and building in the ROS Build Farm.  Approved

**Pull request merged**
