### PR TITLE
Added URDF and mesh files to install target

### PR DESCRIPTION
**Pull request by CameronDevine**
I Modified the CMake file so that URDF and mesh files will be installed.

### CODE REVIEW

**Comment by doronhi** [comment]
Although I don't see a problem, I wander what doesn't work without this change?
Can you give me an example?

**Comment by CameronDevine** [comment]
I realize I should have explained this in the initial pull request.

In its current state, when building `realsense2_camera` in your catkin workspace if you source `catkin_ws/devel/setup.bash` I believe the URDF files can be found by ROS. However if you source `catkin_ws/install/setup.bash` the URDF files will not be in your path, and ROS will not be able to find them.

**Comment by SteveMacenski** [comment]
Moreover, the install space is what is used when releasing a debian package, or when installing software from catkin on another machine 

(also had to fix this on a fork)

**Comment by doronhi** [comment]
Thank you guys. It’ll most likely be in the next release.

**Pull request merged**
