### PR TITLE
ROS2 align pc

### PR DESCRIPTION
**Pull request by doronhi**
modified align_depth option.
if set to true, pointcloud will be build based on the "aligned depth to color" image.
aligning depth image to streams other than color is disabled.

### CODE REVIEW

**Comment by joelbudu** [comment]
Just a quick question about the frame the aligned depth to color pointcloud is published on, both the rgbd.launch package and the deprecated ros2_intel_realsense package publish on the camera_color_optical_frame TF. Is this something the can be applied in this case?

Or rather if I may ask - what does the camera_aligned_depth_to_color_frame represent please?

@doronhi

**Comment by doronhi** [comment]
> Just a quick question about the frame the aligned depth to color pointcloud is published on, both the rgbd.launch package and the deprecated ros2_intel_realsense package publish on the camera_color_optical_frame TF. Is this something the can be applied in this case?
> 
> Or rather if I may ask - what does the camera_aligned_depth_to_color_frame represent please?
> 
> @doronhi

Thank you, that seems like a bug. Fixed.

**Comment by joelbudu** [comment]
@doronhi I found an issue where the realsense2_camera_node sometimes throws a segmentation fault when the node is started and align_depth is set to true.
I'm not sure what causes it but, and seems to be happening randomly, but I'm suspecting it may have something to do with having a subscriber to the /camera/depth/color/points pointcloud topic

**Comment by doronhi** [comment]
> @doronhi I found an issue where the realsense2_camera_node sometimes throws a segmentation fault when the node is started and align_depth is set to true.
> I'm not sure what causes it but, and seems to be happening randomly, but I'm suspecting it may have something to do with having a subscriber to the /camera/depth/color/points pointcloud topic

So far couldn't reproduce.

**Pull request merged**
