### PR TITLE
Added missing zr300 launch file arguments

### PR DESCRIPTION
**Pull request by benmaidel**
Fixes Issue: #258 

Changes proposed in this pull request:
- added missing zr300 arguments to launch file

### CODE REVIEW

**Review by fmessmer — APPROVED** [review]
:+1:

**Comment by fmessmer** [comment]
can this be merged please?

**Review by icarpis — COMMENTED** [review]
Hi @ipa-bnm, thank you for your helping!
There is more work to be done regarding this change. Currently the new parameters appears only in the Launch file and not referenced/published from the source code. As a result, no data is published under the new messages. for instance, there is no data published under /camera/fisheye/camera_info .
Please take a look how we publish the other ROS messages:  depth, rgb, ir, depth_optical_frame_id and etc.

**Comment by benmaidel** [comment]
Hello @icarpis. I think there is a little misunderstanding. This PR is just adding missing launch file params and topic remaps for the zr300 camera. The driver is already reading this params from the parameter server. Take a look here: https://github.com/intel-ros/realsense/blob/indigo-devel/realsense_camera/src/zr300_nodelet.cpp#L98-L112 The zr300 driver is also already publishing imu and fisheye data to the default topic names. To be able to change the topic names I've introduced these two remappings. Also, if we would like the use the `nodelet_rgbd.launch.xml` together with the zr300 camera we need to pass the frame_id params. Otherwise we will not be able to set the frame_ids for `fisheye, fisheye_optical, ir_optical, ir2_optical, imu and imu_optical`. See this Issue https://github.com/intel-ros/realsense/issues/258

For cameras without imu and/or fisheye (r200 for example) this PR should be fine as well, because other realsense camera will just ignore this remaps and params.

**Review by icarpis — APPROVED** [review]
@ipa-bnm, thank you for the clarification.
I ran this PR on ZR300, R200 and SR300 to make sure nothing was broken.

**Pull request merged**
