### PR TITLE
fix: import materials only once

### PR DESCRIPTION
**Pull request by hashb**
This fixes the error `Error: material 'aluminum' is not unique`

This PR takes a different approach to fixing this issue compared to https://github.com/IntelRealSense/realsense-ros/pull/1637 and https://github.com/IntelRealSense/realsense-ros/pull/2325

### CODE REVIEW

**Comment by SamerKhshiboun** [comment]
Hi @hashb 

and thanks for you PR.

As you mentioned there are several PRs regarding this issue:
- #2325 
- #1637 
- #2674 (This PR)

I think that all of them solve the problem, but as I see #1637 is the one with minimal changes.
Do you agree with me ?
If so, I can close other PRs and approve that PR

Thanks,
Samer

**Comment by hashb** [comment]
#1637 doesn't seem to work on ROS2. Thats why I created this PR

**Comment by SamerKhshiboun** [comment]
> #1637 doesn't seem to work on ROS2. Thats why I created this PR

I tried to insert that code manually to ros2-development branch, and it did work for me.
I'm thinking to duplicate that #1637 to ros2-development also.
Did you try it manually ?
https://github.com/IntelRealSense/realsense-ros/pull/1637/files

**Comment by hashb** [comment]
I think I know why #1637 was failing for my use case. It appears that #1637 works when you have multiple cameras of the same type but in my use case, I have different types realsense cameras. I will add a test that verifies this scenario.

**Comment by SamerKhshiboun** [comment]
Thanks @hashb,
Please update me asap so I can figure out how to fix this issue.

On my side, it worked good in both scenarios: 
with two types of same camera, and with two different cameras.

**Comment by hashb** [comment]
I can confirm #1637 works for my use case. Issue I had earlier was likely a bug in my workspace. Closing this PR. Thanks @SamerKhshiboun

**Pull request closed without merging**
