### PR TITLE
chore(realsense2_camera): make reconnect timeout a parameter

### PR DESCRIPTION
**Pull request by JaccovdS**
Currently the reconnect timeout when a device has not been found is hard coded to 6000 ms. This allows for a custom setting through a parameter. Also changed from ms to seconds since this is more convenient for a user.

### CODE REVIEW

**Comment by JaccovdS** [comment]
Can someone maybe take a look?
@doronhi do I have to ping you?

**Comment by reinzor** [comment]
ping @dorodnic

**Comment by doronhi** [comment]
Hi,
Sorry for not paying attention. 
The change seems reasonable. What did you set the parameter to int? why not float? (suppose a user wants to try every 6.5 seconds)

**Comment by reinzor** [comment]
@doronhi thanks for your reply; converting to a float seems reasonable, we will update the PR.

**Comment by doronhi** [comment]
Thanks! I appreciate you didn't neglect even the README.md file :)

**Pull request merged**
