### PR TITLE
Change to Static Transforms for camera

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Switch to using a static transform for the camera as the data does not change.
- Fixes the warning generated when the dynamic transform was used.

### CODE REVIEW

**Comment by reaganlo** [comment]
You may want to remove this from the README or update it with a command relevant to static transforms. https://github.com/intel-ros/realsense/tree/782b2a5261c3f8063287c6cb747193e7f41581ab/realsense_camera#transform-frames

**On a side note**, not related to this PR, the current description for "tf_monitor" is incorrect. It prints on screen instead of generating a pdf. It is "view_frames" that generates the pdf.

**Comment by mdhorn** [comment]
@reaganlo README updated; good catch.

**Comment by rjingar** [comment]
Looks good to me. Approved.

**Comment by reaganlo** [comment]
Approved :+1:

**Pull request merged**
