### PR TITLE
PR for composition implementation and message package name change

### PR DESCRIPTION
**Pull request by JaehyunShim**
@RealSenseSupport @doronhi

As I mentioned in [this issue thread](https://github.com/IntelRealSense/realsense-ros/issues/1336#issuecomment-697073518), I did the followings.

1. Merged realsense2_node to realsense2_camera and implemented it as [Composition](https://index.ros.org/doc/ros2/Tutorials/Composition/). I remember Steve Macenski from Samsung Research also mentioned it in another thread. 
2. Changed message package name to realsense2_camera_msgs for the consistency purpose.

As I mentioned in the issue thread, please redirect this PR to your new branch, desirably 'ros2' branch, and please keep your original code in the current 'eloquent' branch (i suggest you change the name to 'eloquent-devel') since you already binary-released it this month.

Let me know if you have any comments on it, 
Ryan

### CODE REVIEW

**Comment by JaehyunShim** [comment]
Files changed: https://github.com/IntelRealSense/realsense-ros/pull/1415/files

**Comment by JaehyunShim** [comment]
3. I did some more work on the description package. I only added a launch file for the D435 model so please add the rest of the files for other models too.

**Comment by JaehyunShim** [comment]
ping @doronhi

**Comment by JaehyunShim** [comment]
ping @RealSenseSupport

**Comment by doronhi** [comment]
Sorry for so far failing to check your PR. It includes a couple of topics and I won't be able to merge it as a whole.
Unaware of your work I also submitted #1429 for the description package so I'll have to sort all those changes out.
It may take a couple of days. No more, I hope..

**Comment by JaehyunShim** [comment]
@doronhi 

Thank you for your reply. Let me know if you find anything unclear while working on it. 

Jaehyun

**Comment by doronhi** [comment]
Regarding the realsense2_description, if I understand correctly, it is not working yet. In the file view_d435_model.launch.py The keyword "executable" needs to be replaced with "node_executable" and there is no parsing of the urdf.xacro file. I'll skip the description package as I already have #1429 . If you manage to find the time to make some more PRs in the future it would help a lot if it separated into several PRs, each with a single scheme.
Regarding the conversion to Composition - Thanks a lot. I really appreciate these ROS2 specifics.

**Comment by JaehyunShim** [comment]
@doronhi 

Thank you. OK I will keep that in mind next time. Have a great day.

Jaehyun

**Pull request merged**
