### PR TITLE
Load d435.dae properly both for Rviz and Gazebo Ignition

### PR DESCRIPTION
**Pull request by hodnajit**
Current approach leads to error while loading .dae in gazebo

[ign gazebo-7] [Err] [SystemPaths.cc:378] Unable to find file with URI [model://realsense2_description/meshes/d435.dae] [ign gazebo-7] [Err] [SystemPaths.cc:473] Could not resolve file [model://realsense2_description/meshes/d435.dae] [ign gazebo-7] [Err] [MeshManager.cc:173] Unable to find file[model://realsense2_description/meshes/d435.dae] [ign gazebo-7] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [model://realsense2_description/meshes/d435.dae] [ign gazebo-7] [Err] [Ogre2MeshFactory.cc:562] Cannot load null mesh [model://realsense2_description/meshes/d435.dae

### CODE REVIEW

**Review by MarqRazz — COMMENTED** [review]
`realsense-ros` maintainers, is this change something we can get merged? I'm running into the same issues with other camera models.

@hodnajit I suggest you update all of the camera models in `realsense2_description` to use the `file://$(find realsense2_description)` tag.

**Comment by Nir-Az** [comment]
> `realsense-ros` maintainers, is this change something we can get merged? I'm running into the same issues with other camera models.
> 
> @hodnajit I suggest you update all of the camera models in `realsense2_description` to use the `file://$(find realsense2_description)` tag.

Hi @MarqRazz   
We will review it and update this ticket accordingly. 
Thanks

**Comment by MarqRazz** [comment]
Thanks @Nir-Az! 
FYI, I made a fork [here](https://github.com/MarqRazz/realsense-ros/tree/update_mesh_path) with all of the descriptions updated.

**Comment by SamerKhshiboun** [comment]
Hi @MarqRazz @hodnajit 

Should we review this code or the forked one by @MarqRazz ?

If the forked one is the one we want to merge:
- @MarqRazz please open a new PR with its content
- @hodnajit please close this one

Thanks,
Samer

**Comment by hodnajit** [comment]
> Hi @MarqRazz @hodnajit
> 
> Should we review this code or the forked one by @MarqRazz ?
> 
> If the forked one is the one we want to merge:
> 
>     * @MarqRazz please open a new PR with its content
> 
>     * @hodnajit please close this one
> 
> 
> Thanks, Samer

You can review the forked one by @MarqRazz, I am closing this pull request. @MarqRazz please create a new pull request for your changes. :) please, tag me in that PR. 

Thanks Jitka

**Comment by MarqRazz** [comment]
FYI, new PR #2712

**Comment by SamerKhshiboun** [comment]
PR #2712 merged

**Pull request closed without merging**
