### PR TITLE
T265: publish confidence level and remove invalid covariance

### PR DESCRIPTION
**Pull request by schmidtp1**

### CODE REVIEW

**Comment by patrickpoirier51** [comment]
Can we expect this to be merged soon?
Thanks

**Comment by saikishor** [comment]
+1

**Comment by reyes73a** [comment]
an estimate on this? thanks

**Comment by amilcarlucas** [comment]
This needs a rebase and a estimate for a merge date....

**Comment by SamerKhshiboun** [comment]
Hi @schmidtp1 ,
Intel RealSense ROS Wrapper team is focusing on ROS2, as developing ROS1 feature is deprecated.
Beside that, The T265 product will be discontinued as of February 2022. [Reference](https://www.intelrealsense.com/message-to-customers/?_ga=2.266607757.2059295677.1675047606-1846334074.1674552675)
Thanks for your contributing for the RealSense ROS Wrapper.
Closing this PR.

**Pull request closed without merging**
