### PR TITLE
Fix device ID of D405

### PR DESCRIPTION
**Pull request by rhaschke**
The camera is not found with the original ID. Please check!

### CODE REVIEW

**Comment by Nir-Az** [comment]
Hi @rhaschke ,
We currently do not support ROS1 and only focus on ROS2 development.

Looks like the actual D405 PID was never introduced to ROS1 code.
Since this camera is a special case (color stream from depth module), I am not sure this camera will work without code changes and we cannot support this currently.

If you still need it, I suggest forking this branch and verifying this change works for you.

Thanks

**Comment by rhaschke** [comment]
Of course, I verified that the camera works with this fix - both RGB and depth streams.
Would be great if you consider this minor fix to also make the camera available to other users.
Thanks

**Comment by Nir-Az** [comment]
> Of course, I verified that the camera works with this fix - both RGB and depth streams. Would be great if you consider this minor fix to also make the camera available to other users. Thanks

No problem since you verified it we will help and merge it.
FYI, no future release of ROS1 packages is planned.
Thanks for the PR

**Comment by rhaschke** [comment]
Thanks for merging. 

> FYI, no future release of ROS1 packages is planned.

That's fine. I am co-maintaining the [ROS One](https://github.com/ros-o) release, thus we release ourselves.

**Pull request merged**
