### PR TITLE
D455 description

### PR DESCRIPTION
**Pull request by LuAPi**
Add a urdf for the d455.

This is  copy-edited version of the d435 urdf. I think I got the correct measurements but you should probably double check.
It currently doesn't have a mesh. I'm working on that but it's a fairly low priority so someone else might want to add that.

Adding both this and a d435 to the same robot will cause problems without also merging https://github.com/IntelRealSense/realsense-ros/pull/1637

### CODE REVIEW

**Comment by doronhi** [comment]
Thanks. I'll look into it and into the missing mesh.

**Comment by felixvd** [comment]
Sadly I didn't see this PR in https://github.com/IntelRealSense/realsense-ros/issues/1491, so I just duplicated this work. Please use the simplified mesh from my fork: https://github.com/felixvd/realsense-ros/blob/development/realsense2_description/meshes/d455.stl

**Comment by doronhi** [comment]
Thanks for the added mesh.
Something is still not positioned right:
image
The camera_link coordinate system should not be positioned on the glass but rather 4.55mm from it. See **Table 4-11. Depth Cameras Depth Start Point** in [Intel-RealSense-D400-Series-Datasheet-February-2021](https://www.intelrealsense.com/download/15409/?_ga=2.118400585.1764762426.1616396434-146884591.1608633837)
I didn't go further with my examination. Could you verify and/or fix?

**Review by doronhi — CHANGES_REQUESTED** [review]
[See comment](https://github.com/IntelRealSense/realsense-ros/pull/1705#issuecomment-803952279)

**Comment by JHPHELAN** [comment]
I would think the link/joint should be at the back of the camera at or between the mounting screws?

**Comment by doronhi** [comment]
This PR was fixed and merged in #2137.
Thank you for your contribution.

**Pull request closed without merging**
