### PR TITLE
update parsing port_id

### PR DESCRIPTION
**Pull request by doronhi**
dealing with usb_port_id parsing issues referenced in #1085, #1056, #1051, #1036.

### CODE REVIEW

**Comment by jorgemiar** [comment]
I'm running Ubuntu 16.04, Kernel 4.15 and librealsense V2.33.1 on a Up Squared Board. ros-realsense is version 2.2.12 and my camera is the D435i, running V5.12.3. 

I got the `error extracting usb port` when trying to launch the ros node, applied this solution but the error still persists, any ideas why?

My warning message is:

```
[ WARN] [1583584989.992921697]: Error extracting usb port from device with physical ID: 2-2-4
Please report on github issue at https://github.com/IntelRealSense/realsense-ros
```

And the result of rs-enumerate devices:

```
Device info: 
    Name                          : 	Intel RealSense D435I
    Serial Number                 : 	943222071439
    Firmware Version              : 	05.12.03.00
    Recommended Firmware Version  : 	05.12.03.00
    Physical Port                 : 	/sys/devices/pci0000:00/0000:00:15.0/usb2/2-2/2-2:1.0/video4linux/video0
    Debug Op Code                 : 	15
    Advanced Mode                 : 	YES
    Product Id                    : 	0B3A
    Camera Locked                 : 	YES
    Usb Type Descriptor           : 	3.2
    Product Line                  : 	D400
    Asic Serial Number            : 	934123056295
    Firmware Update Id            : 	934123056295
```

**Comment by jorgemiar** [comment]
Update:

I ran `sudo apt purge ros-kinetic-librealsense2 `as suggested by @swinterbotix in #1051 and then rebuilt the catkin_ws using `catkin_make`

I no longer get the `error extracting usb port` warning and the node seems to set up correctly with no other warnings.

Below is the result of running `roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`


```
started roslaunch server http://UP-ASTS:39177/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [21951]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6da73c4a-6090-11ea-ada0-803253dcb3c9
process[rosout-1]: started with pid [21964]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [21981]
process[camera/realsense2_camera-3]: started with pid [21982]
[ INFO] [1583598404.078727851]: Initializing nodelet with 2 worker threads.
[ INFO] [1583598404.268584549]: RealSense ROS v2.2.12
[ INFO] [1583598404.268852019]: Running with LibRealSense v2.33.1
[ INFO] [1583598404.320813647]:  
[ INFO] [1583598404.332296863]: Device with serial number 943222071439 was found.

[ INFO] [1583598404.332394568]: Device with physical ID /sys/devices/pci0000:00/0000:00:15.0/usb2/2-2/2-2:1.0/video4linux/video0 was found.
[ INFO] [1583598404.332478196]: Device with name Intel RealSense D435I was found.
[ INFO] [1583598404.333695438]: Device with port number 2-2 was found.
[ INFO] [1583598404.357680140]: getParameters...
[ INFO] [1583598404.704245579]: setupDevice...
[ INFO] [1583598404.704373567]: JSON file is not provided
[ INFO] [1583598404.704433792]: ROS Node Namespace: camera
[ INFO] [1583598404.704508143]: Device Name: Intel RealSense D435I
[ INFO] [1583598404.704562813]: Device Serial No: 943222071439
[ INFO] [1583598404.704619702]: Device physical port: /sys/devices/pci0000:00/0000:00:15.0/usb2/2-2/2-2:1.0/video4linux/video0
[ INFO] [1583598404.704682758]: Device FW version: 05.12.03.00
[ INFO] [1583598404.704742151]: Device Product ID: 0x0B3A
[ INFO] [1583598404.704818387]: Enable PointCloud: On
[ INFO] [1583598404.704873653]: Align Depth: Off
[ INFO] [1583598404.704926312]: Sync Mode: On
[ INFO] [1583598404.705062496]: Device Sensors: 
[ INFO] [1583598404.705167114]: Stereo Module was found.
[ INFO] [1583598404.705241627]: RGB Camera was found.
[ INFO] [1583598404.705299172]: Motion Module was found.
[ INFO] [1583598404.705424818]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583598404.705487470]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583598404.705541996]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583598404.705600219]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583598404.705675072]: Add Filter: pointcloud
[ INFO] [1583598404.706695843]: num_filters: 1
[ INFO] [1583598404.707349614]: Setting Dynamic reconfig parameters.
[ INFO] [1583598404.950688546]: Done Setting Dynamic reconfig parameters.
[ INFO] [1583598404.985264423]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1583598404.986042240]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1583598404.986438085]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1583598404.997671914]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1583598404.998213865]: setupPublishers...
[ INFO] [1583598405.007451671]: Expected frequency for depth = 30.00000
[ INFO] [1583598405.164742260]: Expected frequency for infra1 = 30.00000
[ INFO] [1583598405.299370400]: Expected frequency for infra2 = 30.00000
[ INFO] [1583598405.456422764]: Expected frequency for color = 30.00000
[ INFO] [1583598405.605814214]: setupStreams...
[ INFO] [1583598405.607050215]: insert Depth to Stereo Module
[ INFO] [1583598405.607183543]: insert Color to RGB Camera
[ INFO] [1583598405.607453222]: insert Infrared to Stereo Module
[ INFO] [1583598405.607523170]: insert Infrared to Stereo Module
[ INFO] [1583598405.607567903]: insert Gyro to Motion Module
[ INFO] [1583598405.607782995]: insert Accel to Motion Module
[ INFO] [1583598405.633333068]: SELECTED BASE:Depth, 0
[ INFO] [1583598405.698460542]: RealSense Node Is Up!
```

**Comment by tmichals** [comment]
I saw your email will document my full results.   On the Nano, it uses a SD card that is flashed from Nvidia.  I have one previously loaded SD card that appears to be able to see the T265, everytime.  So to verify that the install works, I created a new SD card 4/19/20 just to confirm but it is not working  ... when I launch the T265 it is saying it can not find the T265.   I restart the Nano then I run rs-enumerate-devices and it says no devices are pluged in.   I unplug/plug in the T265 then the rs-enumerate-devices finds the T265.   I try launching  "roslaunch realsense2_camera camera:=cam_2 rs_t265.launch serial_no:=845412110091" 

One noticable issue is the device 2-1.1-7 is found by the launch but rs-enumberate-devices says that it is on 2.1.1-6.... of course I set this Physical Port value in the rs_t265.launch file, but it does not seem to matter.(see below)

[ INFO] [1587495461.228606973]: Device with physical ID 2-1.1-7 was found.
[ INFO] [1587495461.228677757]: Device with name Intel RealSense T265 was found.
[ WARN] [1587495461.230371706]: Error extracting usb port from device with physi
Please report on github issue at https://github.com/IntelRealSense/realsense-ros


lcs@lcs:~/catkin_ws$ rs-enumerate-devices
Device info:
    Name                          :     Intel RealSense T265
    Serial Number                 :     0000845412110091
    Firmware Version              :     0.2.0.926
    Physical Port                 :     2-1.1-6
    Product Id                    :     0B37
    Usb Type Descriptor           :     3.1
    Product Line                  :     T200

Stream Profiles supported by Tracking Module
 Supported modes:
    stream       resolution      fps       format
    Fisheye 1     848x800       @ 30Hz     Y8
    Fisheye 2     848x800       @ 30Hz     Y8
    Gyro         N/A            @ 200Hz    MOTION_XYZ32F
    Accel        N/A            @ 62Hz     MOTION_XYZ32F
    Pose         N/A            @ 200Hz    6DOF





[T265.and.D435.launch.issue.Error.extracting.usb.port.from.device.with.physical.ID-.2-1_3-6.txt](https://github.com/IntelRealSense/realsense-ros/files/4512124/T265.and.D435.launch.issue.Error.extracting.usb.port.from.device.with.physical.ID-.2-1_3-6.txt)





I have tried.... sudo apt purge ros-kinetic-librealsense2 and rebuilt the catkin_ws using catkin_make previously with no change.

**Comment by tmichals** [comment]
It is now working!  I am not sure what exactly fixed the issue.  I did do the sudo apt purge ros-melodic-librealsense2 and catkin_make.   I still had the issue with the usb port, above.    Then I edited the rs_t265.launch file and put the full serial number of my T265 with all of the leading zero's.   Everything else is default in the launch file as is installed by the realsense wrapper.   Since I re-start the Nano the T265 seems to keep running... so I need to unplug the T265 and check that it is available with  rs-enumerate-devices... if it is found ... then I am good to launch.   

Let me know if you have any other questions.

**Pull request merged**
