### PR TITLE
Added missing dependency on rgbd_launch

### PR DESCRIPTION
**Pull request by peci1**

### CODE REVIEW

**Comment by doronhi** [comment]
rgbd_launch is not mandatory for running the package. It is merely needed for running `rs_rgbd.launch` which is an example launch file.
You can have the pointcloud directly using filters:=pointcloud.

**Comment by peci1** [comment]
Then it'd maybe deserve at least a comment in the launch file?

**Comment by doronhi** [comment]
Agreed.

**Comment by doronhi** [comment]
Done directly to development branch.
Thank you for helping to clarify.

**Pull request closed without merging**
