### PR TITLE
Allow parametrizing list of reset errors

### PR DESCRIPTION
**Pull request by paulbovbel**
Addresses #889

Allow a parameter to configure which hardware errors will force a camera reset.

### CODE REVIEW

**Comment by doronhi** [comment]
I feel that the whole "reset" option is a "necessary evil", until a permanent solution with firmware, kernel or driver is available.
Therefor, although I have no strong and specific objection to your suggestion, I'm reluctant to add additional code in that section.

**Comment by paulbovbel** [comment]
For the sake of realsense users, I'd urge you to consider including this until "necessary evil" isn't necessary anymore.

**Comment by doronhi** [comment]
What other error messages do you find necessary to include, in addition to the 3 already included?

**Comment by paulbovbel** [comment]
usb_scp_overflow and rec_error both drop the stream, which is recoverable via the soft reset mechanism.

**Comment by amilcarlucas** [comment]
This needs a rebase now :(

**Comment by paulbovbel** [comment]
I'm still using this regularly, but I didn't get the impression maintainers were interested in merging it. If they are, happy to rebase.

**Pull request closed without merging**
