### PR TITLE
Adding a program to find and reset all RealSense cameras.

### PR DESCRIPTION
**Pull request by AndyZe**
Fixes Issue: #205 

Changes proposed in this pull request:
-Automatically find and reset all types of RealSense camera.

You might want to check that I found all possible device #'s for RealSense cameras:

```
reset_all_devices("0a80");

// SR300's

reset_all_devices("0aa5");

reset_all_devices("0ab3");

// ZR300's

reset_all_devices("0ad0");

reset_all_devices("0ACB");
```

### CODE REVIEW

**Review by mattcurfman — CHANGES_REQUESTED** [review]
Is there a way to do this without killing all nodelets?  Would typically expect many nodelets in running system, beyond what are servicing camera.  Wouldn't want to kill all of them?

**Comment by AndyZe** [comment]
Here's a new way to do it. It would be easier if you could give the process a unique name, though, like **realsense_nodelet**. I'm not sure how easy that would be.

**Comment by doronhi** [comment]
I believe that the with the `initial_reset` parameter, the automatic reset following the automatic detection of a problem and the orderly ctrl-C exit, this PR is not necessary anymore.
Would you agree?

**Comment by AndyZe** [comment]
I haven't tried initial_reset, but feel free to close the issue if that's true.

**Comment by joekeo** [comment]
I am currently using a T265 camera and when launching the node with ros 3 out of 5 times the T265 node will fail to start.
I have in the launch file the <arg name="initial_reset"       default="true"/> and <arg name="initial_reset"            value="$(arg initial_reset)"/>

And the camera still does not initialise quite often.
Has anyone been able to solve this and have the camera reliably 'turning on'?

**Comment by amilcarlucas** [comment]
Any progress on this ?

**Comment by AndyZe** [comment]
Three years later, some clients are still having trouble with zombie Realsense ROS nodes. This script was based on `rosnode kill ...`, but that doesn't even work anymore to kill the nodes.

**Pull request closed without merging**
