### PR TITLE
add enable (SetBool) service for disabling/enabling sensor streams

### PR DESCRIPTION
**Pull request by doisyg**
Tested on a D435. More work needed for the T265.
Rewritted the non working toggleSensors method (which was used nowhere) and exposed it as a SetBool enable service.
Addresses https://github.com/IntelRealSense/realsense-ros/issues/1195 and https://github.com/IntelRealSense/librealsense/issues/6413

### CODE REVIEW

**Comment by pmirabel** [comment]
Hi there,
I was wondering if you plan to merge this soon?   
TL;DR :   
I finally found a usecase for that... I have to use depth stream with ROS and RGB stream with a JS app not using ROS, so it began blocking :)

**Comment by doronhi** [comment]
A new wrapper is being built for ROS2 where this functionality is supposed to be built in and use dynamic variables and not services. I rather wait a little and see how it's coming along. If everything will go according to plan we might merge a lot of design changes into this ROS1 wrapper. Therefor I rather not add more interfaces that might be broken in a couple of weeks.

**Comment by doronhi** [comment]
Thanks for this useful ability.

**Comment by YoshuaNava** [comment]
I have found the new function `toggleSensors` to create issues when running with a D430 module. I'll actively report further findings.

Implementation background: See my comment here -> https://github.com/IntelRealSense/realsense-ros/issues/1431#issuecomment-713711508

The issue seems to be related to inter cam sync modes != 0, and the action of opening/closing streams. For some reason, when I set inter cam sync mode = 4 on a D430, and the toggleSensor function tries to close the stream, the sensor disconnects, throwing these messages:

```
[ WARN] [1610619545.575673980] [/realsense_d435/realsense2_camera_manager] : Hardware Notification:Depth stream start failure,1.61062e+12,Error,Hardware Error
[ERROR] [1610619545.575761335] [/realsense_d435/realsense2_camera_manager] : Hardware Reset is needed. use option: initial_reset:=true
 14/01 11:19:06,575 ERROR [140699739600640] (types.h:307) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 14/01 11:19:06,575 ERROR [140699739600640] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 14/01 11:19:06,732 ERROR [140699638953728] (types.h:307) xioctl(VIDIOC_DQBUF) failed for fd: 15 Last Error: No such device
 14/01 11:19:06,732 ERROR [140699638953728] (backend-v4l2.cpp:1310) xioctl(VIDIOC_DQBUF) failed for fd: 15 Last Error: No such device
[ WARN] [1610619546.732844880] [/realsense_d435/realsense2_camera_manager] : Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 15 Last Error: No such device,1.61062e+12,Error,Unknown Error
 14/01 11:19:06,734 ERROR [140699630561024] (types.h:307) xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device
 14/01 11:19:06,734 ERROR [140699630561024] (backend-v4l2.cpp:1310) xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device
[ WARN] [1610619546.734762231] [/realsense_d435/realsense2_camera_manager] : Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device,1.61062e+12,Error,Unknown Error
 14/01 11:19:06,784 ERROR [140699764778752] (types.h:307) Cannot open '/dev/video10 Last Error: No such file or directory
 14/01 11:19:06,784 ERROR [140699764778752] (global_timestamp_reader.cpp:208) Error during time_diff_keeper polling: Cannot open '/dev/video10 Last Error: No such file or directory
[ERROR] [1610619547.082857142] [/realsense_d435/realsense2_camera_manager] : The device has been disconnected!
 14/01 11:19:07,105 ERROR [140699861636864] (types.h:307) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
```

**Comment by YoshuaNava** [comment]
Update on my [previous comment](https://github.com/IntelRealSense/realsense-ros/pull/1313#issuecomment-760110616)

I found a way to overcome the crash with this conditional in the `registerDynamicOption` function:

image

By modifying the `toggleSensors` function:

image

And by adding this block at the bottom of the function `publishTopics`, which sets up the sensor for streaming through ROS:

image

After that, streaming works at the expected rate, without crashing. Do note that I experience [this issue](https://github.com/IntelRealSense/librealsense/issues/7628), but I think it is unrelated to the crashes.

---

All the above was tested with infra1, infra2 and depth enabled. The crash is confirmed to happen on the D430, and the hot-fix to solve the issue.

However, do note that when we ran the sensors with only depth enabled, the driver didn't crash. Enabling infra1/infra2 seems to be related to the crash.

--- 

@dorodnic I would like to submit a PR such that others can benefit from what I have found, but I have the feeling that my solution is a very ad-hoc patch / hack right now. Do you know what could be the reason why the toggleSensors function crashes with the D430 module, but not D435?

For example, is the initialization routine of D430 different to the one for D435x?

**Pull request merged**
