### PR TITLE
Add filling correct Tx, Ty values in projection matrix of right camera.

### LINKED ISSUE #427: Tx,Ty not filled in CameraInfo for infra2
According to the next line Tx, Ty is not filled for right image CameraInfo. As the result, baseline cannot be resolved in a standard ROS way. 
https://github.com/intel-ros/realsense/blob/5210e673ec0d266c62590b433c8b568954f4fdfd/realsense2_camera/src/base_realsense_node.cpp#L828

### PR DESCRIPTION
**Pull request by pavloblindnology**
Fixes https://github.com/intel-ros/realsense/issues/427

### CODE REVIEW

**Comment by doronhi** [comment]
It seems in related to #872.
However, if I understand correctly, we either consider infra2 as a separate monocular camera with a unique frame id, as is now, or consider it a part of the stereo couple as is suggested. In the first option, it's Tx, Ty should be zero, as is now. In the second option, as stated in #872, you are right.

I think that this PR should be merged along with removing infra2 frame id, and maybe some more modification I didn't think about yet.

**Comment by pavloblindnology** [comment]
Well, never used stereo_imag_proc and didn't know about the convention. Instead, I always used stereo cameras as 2 separate cameras with different frames and right camera_info having Tx, Ty filled. So it's up to you to decide what to do with this.

**Comment by doronhi** [comment]
@pavloblindnology , Finally I get to thank you for your PR.
I ended up merging #1242 instead as it incorporates your changes but I thank you for your contribution and support in understanding this concept.

**Comment by doronhi** [comment]
I rebased and updated this PR, including your suggestion regarding the frame_id.
Thanks.

**Pull request merged**
