### PR TITLE
[GL-support] Dynamically switching b/w CPU & GPU processing

### PR DESCRIPTION
**Pull request by Arun-Prasad-V**
Tracked by LRS-1001

### CODE REVIEW

**Comment by Arun-Prasad-V** [comment]
I still need to update the readme for this change.

**Comment by SamerKhshiboun** [comment]
@Arun-Prasad-V, I understand the flow and the mechanism behind this PR. My question is, couldn't we use this function `BaseRealSenseNode::updateSensors()` somehow with some parameters, in order to reduce code duplications?
I see that `StartVideoSensors `and `StopVideoSensors `and also some other parts of the PR are common with `BaseRealSenseNode::updateSensors()`.
It could make the `updateSensors `method longer, and we can split it to multiple functions if needed, but again, my idea is to reuse the same code as much as possible, if that is possible :)

**Comment by Arun-Prasad-V** [comment]
> @Arun-Prasad-V, I understand the flow and the mechanism behind this PR. My question is, couldn't we use this function `BaseRealSenseNode::updateSensors()` somehow with some parameters, in order to reduce code duplications? I see that `StartVideoSensors `and `StopVideoSensors `and also some other parts of the PR are common with `BaseRealSenseNode::updateSensors()`. It could make the `updateSensors `method longer, and we can split it to multiple functions if needed, but again, my idea is to reuse the same code as much as possible, if that is possible :)

Sure, @SamerKhshiboun. Makes sense. will update it.

**Review by SamerKhshiboun — APPROVED** [review]
LGTM

**Pull request merged**
