### PR TITLE
Remove sr300 wake up options

### PR DESCRIPTION
**Pull request by reaganlo**
**Please ensure the above _guidelines for contributing_ are met.**

Fixes Issue: Related to librealsense [PR 240](https://github.com/IntelRealSense/librealsense/pull/240)
Changes proposed in this pull request:
- Temporarily removed the Wake Up options for SR300
- Updated default values for SR300 camera options

### CODE REVIEW

**Comment by mdhorn** [comment]
@reaganlo As discussed, we should revert the changes to defaults for now.

**Comment by reaganlo** [comment]
@mdhorn Done

**Comment by reaganlo** [comment]
@mdhorn As discussed added it back again.

**Comment by mdhorn** [comment]
New defaults match multiple tested cameras with 3.10.xx firmware.

👍  Approved.

**Pull request merged**
