### PR TITLE
Extract a set of commands that are needed to fill dependency.

### PR DESCRIPTION
**Pull request by 130s**
# What does this PR do

The portion of commands that installs the dependency on CI can be reusable, not just for CI, so it's worth making them as a self-contained script so that others can easily download and run.

# Review checklist suggested
- CI.
  - [x]  Same commit has already been tested on our private repos on CI.
  - [ ]  CI on this repo pass.
- [ ] Code review.

CC @geoffreychiou

### CODE REVIEW

**Comment by 130s** [comment]
Turned out this is not review-ready, hence WIPed.

(Btw why Travis CI is not triggered for this and many other PRs?)

**Comment by 130s** [comment]
Updated. Please review.

Btw, I noticed there's no channel for this repo on Travis CI https://travis-ci.org/intel-ros/realsense (or at least I see it says "We couldn't find the repository"). Then I found ROS buildfarm is in use in e.g. https://github.com/intel-ros/realsense/pull/509 (opened in Nov 2018) where [a CI job passed](http://build.ros.org/job/Ipr__realsense_camera__ubuntu_trusty_amd64/279/). What's the status of CI setup on this repo?

**Review by geoffreychiou — APPROVED** [review]

**Comment by SamerKhshiboun** [comment]
Hi @130s ,
Intel RealSense ROS Wrapper team is focusing on ROS2, as developing ROS1 feature is deprecated.
Thanks for your contributing for the RealSense ROS Wrapper.
Closing this PR.

**Comment by SamerKhshiboun** [comment]
Hi @130s 
Intel RealSense ROS Wrapper team is focusing on ROS2, as developing ROS1 feature is deprecated.
Thanks for your contributing for the RealSense ROS Wrapper.
Closing this PR.

**Pull request closed without merging**
