### PR TITLE
Add bond and respawn arg to rs_camera.launch

### PR DESCRIPTION
**Pull request by garaemon**
Add bond and respawn arg to rs_camera.launch like [rs_rgbd.launch](https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_rgbd.launch#L101-L103)

### CODE REVIEW

**Comment by doronhi** [comment]
It will help if you could add some explanation. Thanks :)

**Comment by garaemon** [comment]
@doronhi Thanks. I updated the description.

**Comment by 130s** [comment]
May not be exactly related, but about re-spawning the Realsense ROS nodeo, my team has some update https://github.com/IntelRealSense/librealsense/issues/7151#issuecomment-722614121

**Comment by garaemon** [comment]
I've just rebased the PR to resolve merge conflicts.

**Comment by weeshal** [comment]
Is there any plan to get this merged soon? Wanted to utilize the respawn arg for my application.

**Comment by garaemon** [comment]
I rebased this PR, could you review it?

**Comment by SamerKhshiboun** [comment]
Hi @garaemon ,
Intel RealSense ROS Wrapper team is focusing on ROS2, as developing ROS1 feature is deprecated.
Thanks for your contributing for the RealSense ROS Wrapper.
Closing this PR.

**Pull request closed without merging**
