### PR TITLE
Fix AE getting disabled automatically during init

### PR DESCRIPTION
**Pull request by Arun-Prasad-V**
Tracked on RSDSO-18432

### CODE REVIEW

**Comment by Arun-Prasad-V** [comment]
Closed and re-opened to re-trigger CI.

**Review by Nir-Az — APPROVED** [review]

**Review by SamerKhshiboun — COMMENTED** [review]
I would like to discuss this again with you, before I review this.

**Comment by SamerKhshiboun** [comment]
We have decided to leave this code as is it now?
Or we talked about that this is a user wrong scenario (wrong launch file)?

**Comment by Arun-Prasad-V** [comment]
> We have decided to leave this code as is it now? Or we talked about that this is a user wrong scenario (wrong launch file)?

@SamerKhshiboun, yes, we agreed that it is a wrong scenario (updating exp1,2 and gain 1,2 when HDR is disabled). Please review the PR https://github.com/IntelRealSense/realsense-ros/pull/3007. There I have updated the logic such that, updating exp1,2 and gain1,2 params are not possible when HDR is disabled. We can still use the same `rs_launch.py`.

**Comment by Arun-Prasad-V** [comment]
Closing this PR as this is handled in PR https://github.com/IntelRealSense/realsense-ros/pull/3007.

**Pull request closed without merging**
