### PR TITLE
Add missing dependency std_srvs

### PR DESCRIPTION
**Pull request by Itamare4**

### CODE REVIEW

**Comment by Itamare4** [comment]
@doronhi something seems to be wrong with the Bionic pipeline:
` An exception has been thrown: Failed to resolve request. Request to enable_device_from_file("/home/non_existent_file.txt") was invalid, Reason: Failed to create ros reader: Error opening file: /home/non_existent_file.txt`

**Comment by doronhi** [comment]
> @doronhi something seems to be wrong with the Bionic pipeline:
> ` An exception has been thrown: Failed to resolve request. Request to enable_device_from_file("/home/non_existent_file.txt") was invalid, Reason: Failed to create ros reader: Error opening file: /home/non_existent_file.txt`

The issue was with another tests. Sometimes they fail on the travis but never locally. Should be fixed. For now I reran the test and it passed.

**Comment by doronhi** [comment]
Could you please explain why is this necessary? Under what circumstances "std_srvs" is not installed anyway through other dependencies?
From what I see the following hirarchy exists (in kinetic): rosnode -> rostopic ->rosbag -> std-srvs

Sorry for the late response. I hope you still remember this PR and your motivation.

**Comment by Itamare4** [comment]
I might be too pedant, this issue usually occurs when working on a source-compiled version of ROS. On our units, I usually try to remove all the unnecessary packages(even more than ros-base), and therefore rosbag and std-srvs aren't installed on our units.

**Comment by Itamare4** [comment]
I might be too pedantic, this issue usually occurs when working on a source-compiled version of ROS. On our units, I usually try to remove all the unnecessary packages(even more than ros-base), and therefore rosbag and std-srvs aren't installed on our units.

**Comment by doronhi** [comment]
Sounds reasonable enough.

**Pull request merged**
