### PR TITLE
Changed parameters setting from public to private node handle

### PR DESCRIPTION
**Pull request by Marenix**
Added setting of inter_cam_sync_mode and exposure in .launch file

**(Changes to nodelet.launch.xml and rs_camera.launch are meant only to show the new functionality available with using a private instead of a public node handle for setting parameters. These files should be changed back to their original state before merging)**

EDIT: Related to issue [#1894](https://github.com/IntelRealSense/realsense-ros/issues/1894)

### CODE REVIEW

**Comment by doronhi** [comment]
In several issues we noted that for setting dynamic parameter on startup you could add the following pattern in the rs_camera.launch:

  <rosparam>
      /camera/stereo_module/emitter_on_off: true
  </rosparam>

Your suggestion makes this format impossible and replaces it with asking the users to modify the nodelet.launch.xml, as shown in your example.
My impression is that the current state is more user-friendly. As not all the available parameters are defined in nodelet.launch.xml, it allows users to modify just their own launch files when they wish to set a different parameter.

**Comment by Marenix** [comment]
Thanks for checking this @doronhi 

You're right about adding "/camera/stereo_module/emitter_on_off: true" not working, but this is expected. Using a private node handle changes the namespace a bit, and as you were using the "old" namespace, you couldn't set the parameter. Try using the following pattern in the rs_camera.launch:
/camera/realsense2_camera/stereo_module/emitter_on_off: true

You can also see this change in rqt_reconfigure tool.

**Comment by Marenix** [comment]
Hey @doronhi
Did you get the chance to read my last comment and try the suggestion I wrote there?

**Comment by doronhi** [comment]
Hi @Marenix 
Sorry for the time it took me to come back to you.
I tried changing the parameters while using the existing code and it works by adding the following lines to rs_camera.launch:
```
  <rosparam>
    /camera/stereo_module/inter_cam_sync_mode: 4
  </rosparam>
```
I see that the message: `Hardware Notification:Depth stream start failure` and this is a good sign as 4 in not a valid value.

I then update to private node handler, as you suggest and now I have the parameters names changed so I modify the launch file:
```
  <rosparam>
    /camera/realsense2_camera/stereo_module/inter_cam_sync_mode: 4
  </rosparam>
```
And everything is Ok. Everything works just the same.

It is possible that what you say is true, that it is recommended to use private node handlers (and then I'll ask you to please refer me to where it is recommended) and I may agree that the structure of parameters looks better and more coherent this way,  but it is an interface change.
So far I failed to see what is not working with the current code and I am reluctant to introduce interface changes without a usage benefit. A benefit might be a good reason why it is recommended, a showcase where the current situation causes conflicts or where some parameters cannot be set at the initialization. Any of these or, any other showcase, may help me understand the situation better.

I appreciate it.

**Comment by Marenix** [comment]
Hi @doronhi
I took some time to try a few things again. What you wrote works in both cases, just as you said it. What doesn't work is adding some parameters in launch file the way I did it. I admit, the way you did it is a lot more intuitive and easier to understand. It's also better in a way that you just add it to one place, and you're done.
However, what I found wasn't connected specifically to launch file. I've been using a config file. I've transferred almost all camera parameters there, and am using launch file to load that config file. That's where I first noticed the mentioned problem, where I couldn't set inter_cam_sync_mode if public node handle was used. I just decided to show the problem in launch file, because there is no config file originally in the repository. 

Now, if someone is using a config file, they can't set inter_cam_sync_mode there. The way you changed that parameter works, and that's a good way of setting the parameter when using a launch file, but if that were used while using a config file, it would mean a user would have to modify both the config and launch file to set all the options.

As for whether it's recommended or not using private node handles, I based it on a note I found on one of the official ROS tutorials: http://wiki.ros.org/ROSNodeTutorialC%2B%2B (chapter 3.1). I haven't really come across a case where this would cause me any errors or problems, but I haven't done any extensive testing on it, so I can't say if such a case is likely to happen or not.

**Comment by doronhi** [comment]
Hi @Marenix ,
I appreciate the work you put into this already. I read the comment you referred me to and I'll investigate some more. In the meanwhile, could you please share a config file and a command line you use for reproducing the issue? (Or a shorter version if you prefer)
Thanks

**Comment by Marenix** [comment]
Hi @doronhi,
I added the used config and launch file. I use the following to start it:
`roslaunch realsense2_camera my_rs_camera.launch`
With private node handle, inter_cam_sync_mode is changed, whereas using the public node handle, does not appear to change it. inter_cam_sync_mode is set at the end of the config file, so you can change it there.

**Comment by doronhi** [comment]
Thanks @Marenix ,

I tested with the official version - the one using the public node handles.
In "my_config_file.yaml" file, replacing the lines:
```
  stereo_module:
    inter_cam_sync_mode: 259
```
with this one: 
`/camera/stereo_module/inter_cam_sync_mode: 411`
works.

The comment in the tutorial, chapter 3.1, refers to an issue with running multiple instances of the node. This situation is already dealt with by having all the parameters have a namespace prefix, defined for each instance of the node by the "camera" parameter.
It could be that in retrospect the dynamic parameters should have been written using the private node handle, just as the ROS parameters are written (For instance, "align_depth" uses a private node handle). It could be, and if it came down to it I would investigate the subject some more.
Still, without a failing valid use-case or a functional improvement, I don't see a strong enough reason to introduce an API change.

**Comment by Marenix** [comment]
Hi @doronhi,

Thanks for checking this out. I hadn't thought of trying to add something like:
`/camera/stereo_module/inter_cam_sync_mode: 411`
in config file. You're right, setting the parameter that way work.

If I come across any failing valid use-case in my testing, I'll let you know. But, as you said, parameters already have their own prefixes, so I don't think there should be any clashing of parameter names, and the way you showed me to set parameters works in both cases, so I don't see any problems there now.

Thanks again for taking the time to look at this.

**Comment by doronhi** [comment]
I am closing this PR now.
I really appreciate and thank you for pursuing the subject so and for introducing me to some of the finer details of the node.

**Pull request closed without merging**
