### PR TITLE
new launch parameter for frame distinction in multi camera use

### PR DESCRIPTION
**Pull request by baumanta**
Added a new parameter "tf_prefix" in launch file to be able to use multiple cameras. Before, when multiple cameras were started, all published their topics in frames with the same name (eg. camera_link). Now all cameras can publish to distinct frames (eg. right_camera_link, left_camera_link)

### CODE REVIEW

**Comment by doronhi** [comment]
Sorry for the long delay. It has nothing to do with contributor agreement, just my availability.
Could anyone please explain why other topics (i.e. camera/image_raw) use group's namespace and the static broadcaster for the tf topics (i.e. camera_link) fail to do it?
Anyway, if it is the case then the solution seems ok. I would like to suggest that the default value for tf_prefix will be $(arg camera). Any thoughts?

**Comment by neomanic** [comment]
Commenting here because @baumanta has fixed the issue raised in issues #346, #354, and #448. Yay and thanks!

I was perplexed at first too and it took me more than a few hours to resolve it as per the launch file I posted in #346.

To answer the question @doronhi AFAICT it's because the tf tree is entirely separate from the topics namespacing, which makes a bit of sense if you think of how retrieving sensor data is a separate issue altogether from the sensor's physical location on the robot. 

The following image shows how I have it set up on my robot: the tfs follow the physical build, whereas the topics are set up quite differently: all the sensors are at the root of the tree with a namespace each (so I have /rs_right/*, /rs_left/*, /lidar/*, etc).

tf_tree

I support @doronhi to have the default value `$(arg camera)`. Disclaimer: that's not from knowing whether it's the standard pattern or not, it's just because I don't like it when nodes dump a bajillion tf nodes right into the root /tf namespace and clutter it up.

**Comment by baumanta** [comment]
@doronhi @neomanic thanks for reviewing! I agree, that it would be nice to have the parameters "camera" and "tf_prefix" coupled by default. But if we set the default for "tf_prefix" to camera, then the frames would be named:

camera_camera_link
camera_camera_depth_frame
....

by default. Which I think is not so nice. So one option would be to change the naming convention, such that the frames without prefix are only:  _link, _depth_frame ....
In this case if we default "tf_prefix" to "camera"  we would have:

camera_link
camera_depth_frame

But if the "tf_prefix" is set differently, it would allow for names like:

rs_link
rs_depth_frame ...

If that is ok, I would gladly do those changes!

**Comment by doronhi** [comment]
Thank you both, so much, for your comments. I feel like your second option, @baumanta, of naming the frames without prefix to _link, _depth_frame etc. is very appropriate. As the default namespace is "camera" everything would stay unchanged for those users who didn't face the problem so far. In addition, when the namespace name is changed I don't see a problem with the tf nodes' names change as well.
For users for whom it is important to keep the namespace and the tf names apart it's still an option to bypass the default.
To conclude, I'll be happy if you could change the default value for tf_prefix to be $(arg camera) and also, as you suggested, change "the naming convention, such that the frames without prefix are only: _link, _depth_frame ...."

**Comment by doronhi** [comment]
merged. Thank you guys!

**Pull request merged**
