### PR TITLE
Windows bringup

### PR DESCRIPTION
**Pull request by PranavDhulipala**

### CODE REVIEW

**Comment by Nir-Az** [comment]
Hi @PranavDhulipala , thanks for your contribution.

Can you share some data? what ros distro are you using?
Do you manage to build our ROS wrapper for windows with this change?
@SamerKhshiboun  FYI
Thanks

**Comment by PranavDhulipala** [comment]
Hi @Nir-Az , I used humble distro on Windows. I was able to build and test the ROS wrapper with the changes.

**Comment by Nir-Az** [comment]
@SamerKhshiboun / @MartyG-RealSense  FYI

@PranavDhulipala Great to hear it works for you.
I will merge this change for supporting your UC.

**Review by Nir-Az — APPROVED** [review]
Looks great

**Pull request merged**
